FROM php:7.2.3-apache

COPY . /srv/app
COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf

WORKDIR /srv/app

RUN docker-php-ext-install mbstring pdo pdo_mysql \
    && chown -R www-data:www-data /srv/app

RUN chmod -R 777 /srv

RUN cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
